### ISSUE TITLE
소스코드 이관 시켜 오기

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-bigdata/deep-spot-cloud#1]
현재 소스코드는 개인 계정에서 관리되고 있고, 이를 랩 계정으로 이관 시켜올것.

https://github.com/mjaysonnn/DeepSpotCloud

**Comment by mjaysonnn** [comment]
넵 알겠슴다

2017. 5. 6. 오후 2:25에 "Kyungyong Lee" <notifications@github.com>님이 작성:

**Comment by mjaysonnn** [comment]
Repository transfer to kmu-bigdata requested 했습니다.

**Comment by kmu-leeky** [comment]
This issue was moved to kmu-bigdata/DeepSpotCloud#4
