### ISSUE TITLE
CloudFormation 을 활용한 개발 단계 파이프 라인 구축 가능성 조사

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-bigdata/deep-spot-cloud#2]
https://aws.amazon.com/cloudformation/

활용 가능성 조사

**Comment by kde713** [comment]
@kmu-leeky 
CloudFormation Template Designer를 활용해 전체 서비스 아키텍쳐를 디자인 한다음, git 등과 연계해 구성가능할 것 같습니다.

전체적으로 CloudFormation은 서비스 아키텍쳐의 구조화, 일부 가변 요소를 쉽게 컨트롤 하는 목적으로 설계된 서비스로 보입니다. 여기에 다른 요소를 조금만 연계한다면, 충분히 많은 이점을 가져올 수 있을 것 같습니다.

**Comment by kmu-leeky** [comment]
This issue was moved to kmu-bigdata/DeepSpotCloud#5
